# List all QTLs for two runs

PREFIX dct: <http://purl.org/dc/terms/>
PREFIX gn: <http://genenetwork.org/id/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX gnc: <http://genenetwork.org/category/>
PREFIX gnt: <http://genenetwork.org/term/>
PREFIX sdmx-measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX qb: <http://purl.org/linked-data/cube#>
PREFIX xkos: <http://rdf-vocabulary.ddialliance.org/xkos#>
PREFIX pubmed: <http://rdf.ncbi.nlm.nih.gov/pubmed/>

SELECT DISTINCT ?t ?lod (count(?snp) as ?snps) ?chr ?s ?e WHERE {
# SELECT DISTINCT * WHERE {
  ?traitid a gnt:mappedTrait ;
  gnt:traitId ?t ;
  # MINUS { ?traitid gnt:run gn:test } # use if you want the original GEMMA QTL
  gnt:run gn:test . # use if you want the new QTL
  ?qtl gnt:mappedQTL ?traitid ;
  gnt:qtlChr ?chr ;
  gnt:qtlLOD ?lod ;
  gnt:qtlStart ?start ;
  gnt:qtlStop ?end .
  # ?qtl gnt:mappedSnp ?snp .
  FILTER (?t = "10002") .
} LIMIT 100
